#!/bin/bash
#
# After creating container, run this to set up environment inside container.
#

# Copy your own .bashrc to home dir in the container.
if [ -f .devcontainer/.bashrc ]; then
    cp .devcontainer/.bashrc ~/
fi
if [ -f .devcontainer/.git-completion.sh ]; then
    cp .devcontainer/.git-completion.sh ~/
fi
if [ -f .devcontainer/.git-prompt.sh ]; then
    cp .devcontainer/.git-prompt.sh ~/
fi

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
nvm install --lts --latest-npm
nvm alias default 'lts/*'
echo -e '\n# nvm\n' \
'export NVM_DIR="$HOME/.nvm"\n' \
'[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm\n' \
'[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion\n' \
>> ~/.bashrc
npm install

